
# window customizations
window:
  dimensions:
    columns: 140
    lines: 38
  padding:
    x: 0
    y: 0

  decorations: none

  startup_mode: Maximized

background_opacity: 0.95

font:
  size: 14.0

cursor:
  style: Block
  unfocused_hollow: true

